CREATE TABLE "kosher_places" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" varchar(255) NOT NULL,
	"path" varchar(512) NOT NULL,
	"title" varchar(255) NOT NULL,
	"neighborhood" varchar(80) NOT NULL,
	"neighborhood_label" varchar(120) NOT NULL,
	"tags" json NOT NULL,
	"category_paths" json NOT NULL,
	"tag_paths" json NOT NULL,
	"address" text DEFAULT '' NOT NULL,
	"phone" varchar(40) DEFAULT '' NOT NULL,
	"website" text DEFAULT '' NOT NULL,
	"supervision" text DEFAULT '' NOT NULL,
	"summary" text DEFAULT '' NOT NULL,
	"location_href" text DEFAULT '' NOT NULL,
	"source_captured_at" timestamp,
	"source_type" varchar(40) DEFAULT 'mirror' NOT NULL,
	"source_json" json NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "kosher_places_slug_unique" UNIQUE("slug"),
	CONSTRAINT "kosher_places_path_unique" UNIQUE("path")
);
