// Render-time rewrite of external (Wix / Mailchimp / Wix usrfiles) asset URLs to
// their Vercel Blob equivalents. The map is generated from scripts/blob/asset-map.json
// (see lib/content/generated/asset-blob-map.json) and applied at the render
// chokepoints so mirrored/scraped content serves images from Blob without
// hand-editing the generated content (which gets regenerated by the mirror build).

import assetBlobMap from "@/lib/content/generated/asset-blob-map.json";

const MAP = assetBlobMap as Record<string, string>;

// Hosts we self-host in Blob. Used to find candidate URLs inside HTML strings.
const ASSET_URL_PATTERN =
  /https:\/\/(?:static\.wixstatic\.com|[a-z0-9-]+\.usrfiles\.com|mcusercontent\.com|gallery\.mailchimp\.com)\/[^"'`\\)\s]+/g;

/** Return the Blob URL for a known external asset URL, or the original if unmapped. */
export function toBlobUrl(url: string | null | undefined): string {
  if (!url) {
    return url ?? "";
  }
  return MAP[url] ?? url;
}

/** Rewrite every known external asset URL inside an HTML string to its Blob URL. */
export function rewriteHtmlAssets(html: string): string {
  if (!html) {
    return html;
  }
  return html.replace(ASSET_URL_PATTERN, (match) => MAP[match] ?? match);
}
